import 'package:crypto_font_icons/crypto_font_icons.dart';
const List<String> kcrypto_ticker=['ARDR',
  'BTC',
  'BTS',
  'DCR',
  'DGB',
  'DOGE',
  'ETC',
  'ETH',
  'KMD',
  'LSK',
  'LTC',
  'MAID',
  'REP',
  'STEEM',
  'SYS',
  'USDT',
  'WAVES',
  'XEM',
  'XMR',
  'XRP',
  'ZEC'];

const List<String> kcrypto_name=['ardor',
  'bitcoin',
  'bitshares',
  'decred',
  'digibyte',
  'dogecoin',
  'ethereum-classic',
  'ethereum',
  'komodo',
  'lisk',
  'litecoin',
  'maidsafecoin',
  'augur',
  'steem',
  'syscoin',
  'tether',
  'waves',
  'nem',
  'monero',
  'xrp',
  'zcash'];

const List cryptoicons=[
  CryptoFontIcons.ARDR,
  CryptoFontIcons.BTC,
  CryptoFontIcons.BTS,
  CryptoFontIcons.DCR,
  CryptoFontIcons.DGB,
  CryptoFontIcons.DOGE,
  CryptoFontIcons.ETC,
  CryptoFontIcons.ETH,
  CryptoFontIcons.KMD,
  CryptoFontIcons.LSK,
  CryptoFontIcons.LTC,
  CryptoFontIcons.MAID,
  CryptoFontIcons.REP,
  CryptoFontIcons.STEEM,
  CryptoFontIcons.SYS,
  CryptoFontIcons.USDT,
  CryptoFontIcons.WAVES,
  CryptoFontIcons.XEM,
  CryptoFontIcons.XMR,
  CryptoFontIcons.XRP,
  CryptoFontIcons.ZEC
];


List<String> price=[

];
